### ISSUE TITLE
Mod Folder/localization/gibberish/__data not recognized

### ISSUE THREAD

**Issue by gzzhongqi** [anyabot/LOModInstaller#5]
I am using the newest 1.10 version with Shizuka and Android 14 on a Samsung phone. When the mod folder is like "Mod Folder/localization/__data", the app works fine, but it doesn't work for anything in the form "Mod Folder/localization/gibberish/__data". It gives out the error "__data does not exist in source xxxx in Mod Folder".

**Comment by Altterisk** [comment]
This should fix that, I hope
https://github.com/anyabot/LOModInstaller/releases/tag/1.1.1
Report here once you finished testing

**Comment by gzzhongqi** [comment]
> This should fix that, I hope https://github.com/anyabot/LOModInstaller/releases/tag/1.1.1 Report here once you finished testing

It is indeed working now. Thanks.
