### ISSUE TITLE
It cannot work properly on the mumu emulator (Android emulator)

### ISSUE THREAD

**Issue by devilweime** [anyabot/LOModInstaller#6]
It seems that the application folder management permissions under data cannot be obtained. Some posts say it's not a super user application. I have also tried other Android emulators, but they still don't work properly.
This is a reproduction image：
![screenshots](https://github.com/anyabot/LOModInstaller/assets/36890816/294ad6a1-e118-49fc-9cc8-bd688f68e50f)

**Comment by Altterisk** [comment]
You must select Android/data, not Android/Data/gamefolder (that's for android 13+)

**Comment by devilweime** [comment]
> You must select Android/data, not Android/Data/gamefolder (that's for android 13+)

thanks,it works!
